name: Setup and Generate Protobuf
description: Install protoc and generate protobuf files

runs:
  using: composite
  steps:
    - name: Install protoc
      run: |
        PROTOC_VERSION="29.5"
        curl -sLO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
        sudo unzip -o "protoc-${PROTOC_VERSION}-linux-x86_64.zip" -d /usr/local
        rm "protoc-${PROTOC_VERSION}-linux-x86_64.zip"
        protoc --version
      shell: bash

    - name: Generate protobuf files
      run: |
        cd app
        bash generate_proto.sh
      shell: bash
